#!/bin/bash
ask(){

read -p "what do u want to log" pname
echo $pname >> p.txt
}



fn(){
for pname in $(cat p.txt)
do
ab=$(check $pname)

if [ "$ab" == "0" ];then

a=$(ps -ae | grep $pname | awk '{print $1}')
t=$(ps -p $a -o stime=)
echo "$t">>timelog.txt
fi
done

}


check(){

if ps -ae | grep $1 >> /dev/null ;then
  echo "0"
else 
  return 1
fi
}
#ask
fn
